---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/age19471/lamparinahub.com
    - /bin/cp -f index.html $DEPLOYPATH/index.html
    - /bin/cp -f obrigado.html $DEPLOYPATH/obrigado.html
    - /bin/cp -f enviar.php $DEPLOYPATH/enviar.php
    - /bin/cp -f config.example.php $DEPLOYPATH/config.example.php
    - /bin/cp -Rf css $DEPLOYPATH/
    - /bin/cp -Rf js $DEPLOYPATH/
    - /bin/cp -Rf assets $DEPLOYPATH/
